# Experimentos

## Importando requisitos

In [1]:
import pandas
import os
import numpy
from sklearn.model_selection import GridSearchCV

## Abrindo a planilha

In [2]:
planilha = pandas.read_csv('../Dataset/DataSummary.csv')
planilha

,ID,Type,Name,Train,Test,Class,Length,ED (w=0),DTW (learned_w),DTW (w=100),Default rate,Data donor/editor
0,1,Image,Adiac,390,391,37,176,0.3887,0.3913 (3),0.3964,0.9591,A. Jalba
1,2,Image,ArrowHead,36,175,3,251,0.2000,0.2000 (0),0.2971,0.6057,L. Ye & E. Keogh
2,3,Spectro,Beef,30,30,5,470,0.3333,0.3333 (0),0.3667,0.8000,K. Kemsley & A. Bagnall
3,4,Image,BeetleFly,20,20,2,512,0.2500,0.3000 (7),0.3000,0.5000,J. Hills & A. Bagnall
4,5,Image,BirdChicken,20,20,2,512,0.4500,0.3000 (6),0.2500,0.5000,J. Hills & A. Bagnall
...,...,...,...,...,...,...,...,...,...,...,...,...
123,124,Spectrum,SemgHandMovementCh2,450,450,6,1500,0.6311,0.3622 (1),0.4156,0.8333,C.-C. M. Yeh
124,125,Spectrum,SemgHandSubjectCh2,450,450,5,1500,0.5956,0.2000 (3),0.2733,0.8000,C.-C. M. Yeh
125,126,Sensor,ShakeGestureWiimoteZ,50,50,10,Vary,0.4000,0.1600 (6),0.1400,0.9000,J. Guna
126,127,Simulated,SmoothSubspace,150,150,3,15,0.0933,0.0533 (1),0.1733,0.6667,X. Huang


## Filtrando na planilha os datasets selecionados

In [3]:
planilha = planilha[planilha['ID'].between(97, 128)]
planilha

,ID,Type,Name,Train,Test,Class,Length,ED (w=0),DTW (learned_w),DTW (w=100),Default rate,Data donor/editor
96,97,EOG,EOGVerticalSignal,362,362,12,1250,0.5580,0.5249 (2),0.5525,0.9144,E. Keogh & H. A. Dau
97,98,Spectro,EthanolLevel,504,500,4,1751,0.7260,0.7180 (1),0.7240,0.7480,A. Bagnall
98,99,Sensor,FreezerRegularTrain,150,2850,2,301,0.1951,0.0930 (1),0.1011,0.5000,REFIT project
99,100,Sensor,FreezerSmallTrain,28,2850,2,301,0.3242,0.3242 (0),0.2411,0.5000,REFIT project
100,101,HRM,Fungi,18,186,18,201,0.1774,0.1774 (0),0.1613,0.8978,W. Fonzi
101,102,Trajectory,GestureMidAirD1,208,130,26,Vary,0.4231,0.3615 (5),0.4308,0.9615,H. A. Dau
102,103,Trajectory,GestureMidAirD2,208,130,26,Vary,0.5077,0.4000 (6),0.3923,0.9615,H. A. Dau
103,104,Trajectory,GestureMidAirD3,208,130,26,Vary,0.6538,0.6231 (1),0.6769,0.9615,H. A. Dau
104,105,Sensor,GesturePebbleZ1,132,172,6,Vary,0.2674,0.1744 (2),0.2093,0.8140,I. Maglogiannis
105,106,Sensor,GesturePebbleZ2,146,158,6,Vary,0.3291,0.2215 (6),0.3291,0.8101,I. Maglogiannis


## Realizando experimentos no dataset da primeira linha da tabela

Obtendo o caminho do dataset de exemplo

In [4]:
dataset_exemplo = planilha.iloc[0]['Name']
dataset_exemplo

'EOGVerticalSignal'

In [5]:
dataset_dirname = os.path.join('../Dataset/UCRArchive_2018', dataset_exemplo)
dataset_dirname

'../Dataset/UCRArchive_2018/EOGVerticalSignal'

In [6]:
caminho_arquivo_treino = os.path.join(dataset_dirname, '{}_TRAIN.tsv'.format(dataset_exemplo))
caminho_arquivo_treino

'../Dataset/UCRArchive_2018/EOGVerticalSignal/EOGVerticalSignal_TRAIN.tsv'

In [7]:
caminho_arquivo_teste = os.path.join(dataset_dirname, '{}_TEST.tsv'.format((dataset_exemplo)))
caminho_arquivo_teste

'../Dataset/UCRArchive_2018/EOGVerticalSignal/EOGVerticalSignal_TEST.tsv'

Abrindo datasets

In [8]:
dataset_exemplo_treino = pandas.read_csv(caminho_arquivo_treino, sep='\t', header=None)
dataset_exemplo_treino

,0,1,2,3,4,5,6,7,8,9,...,1241,1242,1243,1244,1245,1246,1247,1248,1249,1250
0,1,-5.70320,-5.89550,-5.88780,-6.08000,-6.17230,-6.26460,-6.2568,-6.1491,-6.4414,...,-113.3100,-113.4100,-113.50000,-114.390000,-114.4800,-113.77000,-113.0700,-113.1600,-112.8500,-112.9400
1,1,-2.18020,-2.30860,-2.33690,-2.36520,-2.39360,-2.02190,-2.0502,-2.0786,-2.5069,...,108.3900,108.5600,108.53000,108.500000,108.4700,108.45000,108.4200,108.3900,108.1600,108.1300
2,1,6.70950,6.52680,6.34420,6.16160,5.97900,5.79640,5.6137,4.5311,2.7485,...,-34.9360,-35.1190,-35.30100,-35.484000,-35.6660,-34.94900,-35.1320,-35.3140,-34.5970,-34.7800
3,1,-0.91251,-0.72238,-0.53226,-0.74213,-0.95201,-1.16190,-1.5718,-1.7816,-1.1915,...,-173.8600,-174.0700,-173.68000,-173.890000,-174.7000,-174.71000,-174.9200,-175.1300,-174.7400,-174.3500
4,1,-5.44400,-5.32610,-4.10820,-3.69020,-3.57230,-3.45440,-3.0364,-2.6185,-2.5006,...,2.0864,1.8044,1.92230,2.040200,2.1582,2.27610,2.3940,2.5119,2.6299,2.7478
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
357,12,-4.32250,-2.52830,-2.83410,-2.83980,-2.84560,-2.85130,-4.3571,-4.3629,-4.3686,...,-2.1725,-1.3783,-0.08404,-0.089806,1.5044,-0.10134,-1.1071,-1.1129,-1.3186,-1.3244
358,12,-5.91600,-5.90050,-6.68500,-7.76950,-7.75400,-7.73850,-6.6230,-6.6075,-6.5920,...,32.0100,28.3260,25.44100,27.857000,32.0720,32.08800,31.9030,27.9190,27.9340,27.9500
359,12,2.66670,2.60940,2.55220,4.59490,1.63760,0.38033,2.4231,4.0658,2.3085,...,-42.8540,-42.9110,-42.96900,-43.026000,-44.3830,-45.84000,-44.4980,-44.5550,-44.6120,-47.1690
360,12,-1.22680,-1.24790,1.63100,1.50990,1.38880,3.16770,3.0465,2.9254,3.4043,...,-97.5090,-94.3310,-97.75200,-94.573000,-94.6940,-94.81500,-94.9360,-98.0570,-102.5800,-102.7000


In [9]:
dataset_exemplo_teste = pandas.read_csv(caminho_arquivo_teste, sep='\t', header=None)
dataset_exemplo_teste

,0,1,2,3,4,5,6,7,8,9,...,1241,1242,1243,1244,1245,1246,1247,1248,1249,1250
0,1,2.67520,2.68930,3.2034,4.01750,3.93150,3.94560,3.55970,3.87380,3.48790,...,-394.470,-392.450,-391.240,-390.830,-390.710,-390.900,-390.980,-390.870,-390.850,-390.740
1,1,6.84840,6.17140,5.6944,5.31730,5.14030,4.96330,4.18620,3.60920,2.73220,...,-145.670,-144.850,-144.220,-143.900,-143.680,-143.860,-143.530,-144.210,-144.790,-144.960
2,1,-4.91380,-4.87180,-4.8298,-4.98790,-5.14590,-4.50390,-4.66190,-3.72000,-3.57800,...,-169.270,-169.430,-169.590,-169.140,-169.100,-169.260,-169.420,-169.980,-170.730,-170.890
3,1,18.27800,18.29000,18.3020,18.31400,18.32600,19.13800,19.15000,19.86200,19.17400,...,308.330,307.840,308.350,307.670,307.380,308.290,308.300,308.310,307.830,307.840
4,1,-6.26350,-6.28940,-6.0153,-5.34120,-5.46710,-6.09300,-6.71890,-6.34470,-6.47060,...,39.229,38.503,38.077,37.551,37.425,36.499,36.374,37.048,36.922,36.796
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
357,12,2.02960,1.62900,1.2284,0.92786,0.72729,0.42672,0.42615,0.12558,0.12501,...,-12.375,-14.576,-14.576,-12.577,-12.577,-11.278,-11.279,-12.579,-11.280,-12.580
358,12,1.39790,1.59650,1.6951,0.89369,1.09230,1.29090,0.28948,0.08808,0.28668,...,132.660,132.460,132.660,132.850,133.450,133.950,133.850,134.050,133.850,134.350
359,12,1.90450,1.74240,1.8803,3.41830,2.15620,1.99420,2.13210,3.97010,4.10800,...,93.154,92.992,92.630,92.068,90.606,89.744,89.282,89.020,88.758,88.896
360,12,17.80400,16.97900,16.5540,16.02900,15.70400,15.07800,14.75300,13.22800,11.50300,...,-419.660,-419.990,-420.310,-420.040,-420.060,-420.390,-420.510,-420.840,-421.160,-421.490


### Formatando Dataset

In [10]:
def formatar_dataset(df: pandas.DataFrame) -> pandas.DataFrame:
    """
    Realiza a formatação do dataset.
    :param df: Dataset a ser formatado.
    :return: Dataset formatado.
    """
    classe = df.iloc[:, 0]
    series = df.iloc[:, 1:]

    df_novo = pandas.DataFrame({
        'classe': classe,
        'SérieTemporal': list(series.to_numpy())
    })

    return df_novo

In [11]:
dataset_exemplo_treino = formatar_dataset(dataset_exemplo_treino)
dataset_exemplo_treino

,classe,SérieTemporal
0,1,"[-5.7032, -5.8955, -5.8878, -6.08, -6.1723, -6..."
1,1,"[-2.1802, -2.3086, -2.3369, -2.3652, -2.3936, ..."
2,1,"[6.7095, 6.5268, 6.3442, 6.1616, 5.979, 5.7964..."
3,1,"[-0.91251, -0.72238, -0.53226, -0.74213, -0.95..."
4,1,"[-5.444, -5.3261, -4.1082, -3.6902, -3.5723, -..."
...,...,...
357,12,"[-4.3225, -2.5283, -2.8341, -2.8398, -2.8456, ..."
358,12,"[-5.916, -5.9005, -6.685, -7.7695, -7.754, -7...."
359,12,"[2.6667, 2.6094, 2.5522, 4.5949, 1.6376, 0.380..."
360,12,"[-1.2268, -1.2479, 1.631, 1.5099, 1.3888, 3.16..."


In [12]:
dataset_exemplo_teste = formatar_dataset(dataset_exemplo_teste)
dataset_exemplo_teste

,classe,SérieTemporal
0,1,"[2.6752, 2.6893, 3.2034, 4.0175, 3.9315, 3.945..."
1,1,"[6.8484, 6.1714, 5.6944, 5.3173, 5.1403, 4.963..."
2,1,"[-4.9138, -4.8718, -4.8298, -4.9879, -5.1459, ..."
3,1,"[18.278, 18.29, 18.302, 18.314, 18.326, 19.138..."
4,1,"[-6.2635, -6.2894, -6.0153, -5.3412, -5.4671, ..."
...,...,...
357,12,"[2.0296, 1.629, 1.2284, 0.92786, 0.72729, 0.42..."
358,12,"[1.3979, 1.5965, 1.6951, 0.89369, 1.0923, 1.29..."
359,12,"[1.9045, 1.7424, 1.8803, 3.4183, 2.1562, 1.994..."
360,12,"[17.804, 16.979, 16.554, 16.029, 15.704, 15.07..."


### Aplicando algoritmos nos datasets

In [13]:
from app.model.DynamicTimeWarping import DynamicTimeWarping
from app.model.DerivativeDynamicTimeWarping import DerivativeDynamicTimeWarping
from app.model.LongestCommonSubsequence import LongestCommonSubsequence
from app.model.SoftDynamicTimeWarping import SoftDynamicTimeWarping

def aplicar_algoritmos_series_temporais(dataset: pandas.DataFrame, indice_serie_referencia: int = 0) -> pandas.DataFrame:
    """
    Aplica algoritmos às séries temporais.
    :param dataset: Dataset.
    :param indice_serie_referencia: Índice da série temporal de referência.
    :return: Dataset com as distâncias das séries temporais.
    """
    # Instanciando algoritmos
    dtw = DynamicTimeWarping()
    ddtw = DerivativeDynamicTimeWarping()
    lcs = LongestCommonSubsequence()
    soft_dtw = SoftDynamicTimeWarping()

    # Definindo série de referência
    serie_referencia = dataset.iloc[indice_serie_referencia]["SérieTemporal"]

    # Executando algoritmos e adicionando ao Dataset
    print('Executando Dynamic Time Warping')
    dataset['dtw'] = dataset['SérieTemporal'].apply(
        lambda s: dtw.obter_distancia(s, serie_referencia)
    )
    print('Finalizado o Dynamic Time Warping')

    print('Executando o Derivative Dynamic Time Warping')
    dataset['ddtw'] = dataset['SérieTemporal'].apply(
        lambda s: ddtw.obter_distancia(s, serie_referencia)
    )
    print('Finalizado o Derivative Dynamic Time Warping')

    print('Executando o Longest Common Subsequence')
    dataset['lcs'] = dataset['SérieTemporal'].apply(
        lambda s: lcs.lcs(s, serie_referencia)
    )
    print('Finalizado o Longest Common Subsequence')

    print('Executando o Soft Dynamic Time Warping')
    dataset['soft-dtw'] = dataset['SérieTemporal'].apply(
        lambda s: soft_dtw.obter_distancia(s, serie_referencia)
    )
    print('Finalizado o Soft Dynamic Time Warping')

    return dataset

Função auxiliar

In [14]:
import os
import pathlib
import json

def salvar_como_json(dados: object, filepath: str):
    """
    Salva um objeto como JSON.
    :param dados: Objeto a ser salvo
    :param filepath: Caminho do arquivo onde será salvo o objeto.
    :return:
    """

    # Criando o diretório pai, caso ele não exista
    os.makedirs(pathlib.Path(filepath).parent, exist_ok=True)

    with open(filepath, 'w', encoding='utf-8') as arquivo:
        json.dump(dados, arquivo, indent=4, ensure_ascii=False)

In [15]:
def carregar_arquivo_json(filepath: str) -> object:
    """
    Carrega um arquivo JSON.
    :param filepath: Caminho do arquivo onde será lido o objeto.
    :return: Objeto carregado a partir do arquivo JSON.
    """
    with open(filepath, 'r', encoding='utf-8') as arquivo:
        return json.load(arquivo)

In [16]:
dataset_exemplo_treino = aplicar_algoritmos_series_temporais(dataset_exemplo_treino)

Executando Dynamic Time Warping
Finalizado o Dynamic Time Warping
Executando o Derivative Dynamic Time Warping
Finalizado o Derivative Dynamic Time Warping
Executando o Longest Common Subsequence
Finalizado o Longest Common Subsequence
Executando o Soft Dynamic Time Warping
Finalizado o Soft Dynamic Time Warping


In [17]:
dataset_exemplo_teste = aplicar_algoritmos_series_temporais(dataset_exemplo_teste)

Executando Dynamic Time Warping
Finalizado o Dynamic Time Warping
Executando o Derivative Dynamic Time Warping
Finalizado o Derivative Dynamic Time Warping
Executando o Longest Common Subsequence
Finalizado o Longest Common Subsequence
Executando o Soft Dynamic Time Warping
Finalizado o Soft Dynamic Time Warping


Salvando os datasets como Pickle

In [18]:
dataset_exemplo_treino.to_pickle('../Dataset/processed/dataset_exemplo_treino.pkl')
dataset_exemplo_teste.to_pickle('../Dataset/processed/dataset_exemplo_teste.pkl')

### Analisando modelo

Carregando os dados a partir do arquivo Pickle

In [63]:
dataset_exemplo_treino = pandas.read_pickle('../Dataset/processed/dataset_exemplo_treino.pkl')
dataset_exemplo_teste = pandas.read_pickle('../Dataset/processed/dataset_exemplo_teste.pkl')

In [64]:
dataset_exemplo_treino

,classe,SérieTemporal,dtw,ddtw,lcs,soft-dtw
0,1,"[-5.7032, -5.8955, -5.8878, -6.08, -6.1723, -6...",0.000000,0.000000,1250,-1.625967e+03
1,1,"[-2.1802, -2.3086, -2.3369, -2.3652, -2.3936, ...",94123.211165,417.935442,1249,1.490889e+07
2,1,"[6.7095, 6.5268, 6.3442, 6.1616, 5.979, 5.7964...",30054.421325,420.707073,1249,1.901112e+06
3,1,"[-0.91251, -0.72238, -0.53226, -0.74213, -0.95...",14798.394310,481.370766,1249,5.967205e+05
4,1,"[-5.444, -5.3261, -4.1082, -3.6902, -3.5723, -...",65684.048861,471.058642,1249,5.371476e+06
...,...,...,...,...,...,...
357,12,"[-4.3225, -2.5283, -2.8341, -2.8398, -2.8456, ...",50358.440768,1368.307540,1249,4.388884e+06
358,12,"[-5.916, -5.9005, -6.685, -7.7695, -7.754, -7....",66425.290402,1557.679812,1249,7.836528e+06
359,12,"[2.6667, 2.6094, 2.5522, 4.5949, 1.6376, 0.380...",27812.949282,1445.712285,1249,1.841132e+06
360,12,"[-1.2268, -1.2479, 1.631, 1.5099, 1.3888, 3.16...",9598.673229,1463.615157,1249,5.416825e+05


In [65]:
dataset_exemplo_teste

,classe,SérieTemporal,dtw,ddtw,lcs,soft-dtw
0,1,"[2.6752, 2.6893, 3.2034, 4.0175, 3.9315, 3.945...",0.000000,0.000000,1250,-1.305859e+03
1,1,"[6.8484, 6.1714, 5.6944, 5.3173, 5.1403, 4.963...",138552.297586,851.164827,1249,3.058980e+07
2,1,"[-4.9138, -4.8718, -4.8298, -4.9879, -5.1459, ...",123473.825114,686.366269,1249,2.502971e+07
3,1,"[18.278, 18.29, 18.302, 18.314, 18.326, 19.138...",388746.788923,1044.108816,1249,2.376134e+08
4,1,"[-6.2635, -6.2894, -6.0153, -5.3412, -5.4671, ...",243547.011488,988.764721,1249,9.044747e+07
...,...,...,...,...,...,...
357,12,"[2.0296, 1.629, 1.2284, 0.92786, 0.72729, 0.42...",214950.506791,1687.177069,1249,7.679610e+07
358,12,"[1.3979, 1.5965, 1.6951, 0.89369, 1.0923, 1.29...",260197.594951,1514.643888,1249,1.175823e+08
359,12,"[1.9045, 1.7424, 1.8803, 3.4183, 2.1562, 1.994...",273938.258348,1601.578512,1249,1.194652e+08
360,12,"[17.804, 16.979, 16.554, 16.029, 15.704, 15.07...",14170.937077,1504.518601,1249,1.302145e+06


In [66]:
dataset_exemplo_treino['classe'].value_counts()

classe
6     31
7     31
1     30
2     30
3     30
4     30
5     30
8     30
9     30
10    30
11    30
12    30
Name: count, dtype: int64

### Criando conjuntos de teste e treino

Obtendo conjuntos de treino e teste: x e y

In [70]:
def separar_x_y(dataset: pandas.DataFrame) -> tuple[list, list]:
    """
    Separa o conjunto de treino do conjunto de teste
    :param dataset: Dataset de entrada.
    :return: Tupla com os cunjuntos de treino e teste.
    """
    x = (dataset['SérieTemporal'] + dataset['dtw'] + dataset['ddtw'] + dataset['lcs'] + dataset['soft-dtw']).tolist()

    y = dataset['classe'].tolist()

    return x, y

In [71]:
x_train, y_train = separar_x_y(dataset_exemplo_treino)

In [72]:
x_train

[array([-381.66989436, -381.86219436, -381.85449436, ..., -489.12669436,
        -488.81669436, -488.90669436], shape=(1250,)),
 array([15004676.13852603, 15004676.01012603, 15004675.98182603, ...,
        15004786.70872603, 15004786.47872603, 15004786.44872603],
       shape=(1250,)),
 array([1932843.14432783, 1932842.96162783, 1932842.77902783, ...,
        1932801.12082783, 1932801.83782783, 1932801.65482783],
       shape=(1250,)),
 array([613248.32199684, 613248.51212684, 613248.70224684, ...,
        613074.10450684, 613074.49450684, 613074.88450684], shape=(1250,)),
 array([5438874.24168062, 5438874.35958062, 5438875.57748062, ...,
        5438882.19758062, 5438882.31558062, 5438882.43348062],
       shape=(1250,)),
 array([21617097.06453982, 21617097.69753982, 21617098.03053982, ...,
        21617228.90153982, 21617228.63153982, 21617229.17153982],
       shape=(1250,)),
 array([50503489.64387698, 50503490.38187698, 50503490.32087698, ...,
        50502958.97787698, 50502958.21

In [73]:
y_train

[1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 12,
 12,
 12,
 12,
 12,
 12,
 12,
 12,
 12,
 12,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 12,
 12,
 12,
 12,
 12,
 12,


In [74]:
x_test, y_test = separar_x_y(dataset_exemplo_teste)

### Treinando modelo

Normalizando os dados

In [75]:
from sklearn.preprocessing import StandardScaler

In [76]:
scaler = StandardScaler()

x_train = scaler.fit_transform(x_train)
x_test = scaler.fit_transform(x_test)

Criando e treinando modelo KNeighbors

In [77]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import GridSearchCV

In [87]:
parametros = {'n_neighbors': [1, 3, 5, 7, 9, 11]}
knn = KNeighborsClassifier()
grid = GridSearchCV(knn, parametros, cv=5)
grid.fit(x_train, y_train)
knn.fit(x_train, y_train)

,"n_neighbors n_neighbors: int, default=5Number of neighbors to use by default for :meth:`kneighbors` queries.",5
,"weights weights: {'uniform', 'distance'}, callable or None, default='uniform'Weight function used in prediction. Possible values:- 'uniform' : uniform weights. All points in each neighborhood are weighted equally.- 'distance' : weight points by the inverse of their distance. in this case, closer neighbors of a query point will have a greater influence than neighbors which are further away.- [callable] : a user-defined function which accepts an array of distances, and returns an array of the same shape containing the weights.Refer to the example entitled:ref:`sphx_glr_auto_examples_neighbors_plot_classification.py`showing the impact of the `weights` parameter on the decisionboundary.",'uniform'
,"algorithm algorithm: {'auto', 'ball_tree', 'kd_tree', 'brute'}, default='auto'Algorithm used to compute the nearest neighbors:- 'ball_tree' will use :class:`BallTree`- 'kd_tree' will use :class:`KDTree`- 'brute' will use a brute-force search.- 'auto' will attempt to decide the most appropriate algorithm based on the values passed to :meth:`fit` method.Note: fitting on sparse input will override the setting ofthis parameter, using brute force.",'auto'
,"leaf_size leaf_size: int, default=30Leaf size passed to BallTree or KDTree. This can affect thespeed of the construction and query, as well as the memoryrequired to store the tree. The optimal value depends on thenature of the problem.",30
,"p p: float, default=2Power parameter for the Minkowski metric. When p = 1, this is equivalentto using manhattan_distance (l1), and euclidean_distance (l2) for p = 2.For arbitrary p, minkowski_distance (l_p) is used. This parameter is expectedto be positive.",2
,"metric metric: str or callable, default='minkowski'Metric to use for distance computation. Default is ""minkowski"", whichresults in the standard Euclidean distance when p = 2. See thedocumentation of `scipy.spatial.distance<https://docs.scipy.org/doc/scipy/reference/spatial.distance.html>`_ andthe metrics listed in:class:`~sklearn.metrics.pairwise.distance_metrics` for valid metricvalues.If metric is ""precomputed"", X is assumed to be a distance matrix andmust be square during fit. X may be a :term:`sparse graph`, in whichcase only ""nonzero"" elements may be considered neighbors.If metric is a callable function, it takes two arrays representing 1Dvectors as inputs and must return one value indicating the distancebetween those vectors. This works for Scipy's metrics, but is lessefficient than passing the metric name as a string.",'minkowski'
,"metric_params metric_params: dict, default=NoneAdditional keyword arguments for the metric function.",None
,"n_jobs n_jobs: int, default=NoneThe number of parallel jobs to run for neighbors search.``None`` means 1 unless in a :obj:`joblib.parallel_backend` context.``-1`` means using all processors. See :term:`Glossary <n_jobs>`for more details.Doesn't affect :meth:`fit` method.",None
Name,Type,Value
"classes_ classes_: array of shape (n_classes,)Class labels known to the classifier","ndarray[int64](12,)","[ 1, 2, 3,...,10,11,12]"
"effective_metric_ effective_metric_: str or callbleThe distance metric used. It will be same as the `metric` parameteror a synonym of it, e.g. 'euclidean' if the `metric` parameter set to'minkowski' and `p` parameter set to 2.",str,'eu...an'


Realizando predições

In [88]:
y_pred = knn.predict(x_test)
y_pred

array([ 6,  6,  6,  1,  4,  5,  4,  1,  3,  6,  6,  6,  6,  6,  6,  6,  6,
        6,  5,  5,  6,  6,  6,  6,  6,  6,  6,  6,  6,  5,  5,  6,  6,  6,
        6,  6,  6,  5,  6,  6,  1,  1,  5,  1,  1,  1,  1,  1,  1,  5,  6,
        5,  5,  6,  5,  5,  5,  6,  5,  6,  4,  6,  5,  5,  4,  6,  5,  5,
        5,  5,  6,  6,  6,  5,  6,  6,  4,  5,  2,  5,  6,  5,  5,  5,  4,
        4,  3,  5,  5,  4,  4,  6,  6,  6,  3,  6,  6,  6,  5,  5,  5,  6,
        6,  6,  6,  3,  6,  5,  5,  5,  2,  5,  5,  4,  5,  5,  4,  5,  2,
        4,  5,  6,  1,  1,  1,  5,  6,  5,  1,  6,  1,  5,  5,  7,  5,  6,
       11,  6,  6,  6,  6,  5,  4,  6,  9,  5,  6,  6,  5,  6,  1,  4,  6,
        6,  5,  5,  6,  6,  6,  6,  6,  1,  1,  2,  1,  1,  1,  1,  4,  5,
        3,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  5,  9,  5,  5,  5,  5,
        6,  6,  1,  3,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  5,  5,
        4,  5,  5,  3,  2,  6,  6,  4,  6,  6,  6,  6,  6,  6,  6,  6,  6,
        6,  6,  2,  6,  5

Avaliando modelo

In [89]:
from sklearn.metrics import accuracy_score

In [90]:
acuracia = accuracy_score(y_test, y_pred)
acuracia

0.10220994475138122

Criando e treinando modelo SVM

In [92]:
import sklearn.svm

In [94]:
svm = sklearn.svm.SVC()
svm.fit(x_train, y_train)

,"C C: float, default=1.0Regularization parameter. The strength of the regularization isinversely proportional to C. Must be strictly positive. The penaltyis a squared l2 penalty. For an intuitive visualization of the effectsof scaling the regularization parameter C, see:ref:`sphx_glr_auto_examples_svm_plot_svm_scale_c.py`.",1.0
,"kernel kernel: {'linear', 'poly', 'rbf', 'sigmoid', 'precomputed'} or callable, default='rbf'Specifies the kernel type to be used in the algorithm. Ifnone is given, 'rbf' will be used. If a callable is given it is used topre-compute the kernel matrix from data matrices; that matrix should bean array of shape ``(n_samples, n_samples)``. For an intuitivevisualization of different kernel types see:ref:`sphx_glr_auto_examples_svm_plot_svm_kernels.py`.",'rbf'
,"degree degree: int, default=3Degree of the polynomial kernel function ('poly').Must be non-negative. Ignored by all other kernels.",3
,"gamma gamma: {'scale', 'auto'} or float, default='scale'Kernel coefficient for 'rbf', 'poly' and 'sigmoid'.- if ``gamma='scale'`` (default) is passed then it uses 1 / (n_features * X.var()) as value of gamma,- if 'auto', uses 1 / n_features- if float, must be non-negative... versionchanged:: 0.22 The default value of ``gamma`` changed from 'auto' to 'scale'.",'scale'
,"coef0 coef0: float, default=0.0Independent term in kernel function.It is only significant in 'poly' and 'sigmoid'.",0.0
,"shrinking shrinking: bool, default=TrueWhether to use the shrinking heuristic.See the :ref:`User Guide <shrinking_svm>`.",True
,"probability probability: bool, default=FalseWhether to enable probability estimates. This must be enabled priorto calling `fit`, will slow down that method as it internally uses5-fold cross-validation, and `predict_proba` may be inconsistent with`predict`. Read more in the :ref:`User Guide <scores_probabilities>`...deprecated:: 1.9 The `probability` parameter is deprecated and will be removed in 1.11. Use `CalibratedClassifierCV(SVC(), ensemble=False)` instead of `SVC(probability=True)`.",'deprecated'
,"tol tol: float, default=1e-3Tolerance for stopping criterion.",0.001
,"cache_size cache_size: float, default=200Specify the size of the kernel cache (in MB).",200
,"class_weight class_weight: dict or 'balanced', default=NoneSet the parameter C of class i to class_weight[i]*C forSVC. If not given, all classes are supposed to haveweight one.The ""balanced"" mode uses the values of y to automatically adjustweights inversely proportional to class frequencies in the input dataas ``n_samples / (n_classes * np.bincount(y))``.",None
,"verbose verbose: bool, default=FalseEnable verbose output. Note that this setting takes advantage of aper-process runtime setting in libsvm that, if enabled, may not workproperly in a multithreaded context.",False


Realizando predições

In [96]:
y_pred = svm.predict(x_test)
y_pred

array([6, 6, 6, 1, 5, 5, 5, 1, 5, 6, 6, 6, 6, 6, 6, 6, 6, 6, 7, 5, 6, 6,
       6, 6, 6, 6, 6, 6, 6, 5, 5, 6, 6, 6, 6, 6, 6, 5, 6, 6, 1, 1, 5, 5,
       5, 1, 5, 5, 1, 5, 6, 5, 5, 6, 5, 5, 5, 6, 7, 6, 5, 6, 5, 5, 5, 6,
       5, 5, 7, 5, 6, 6, 6, 7, 6, 6, 5, 5, 6, 5, 6, 5, 7, 5, 5, 5, 5, 5,
       5, 5, 5, 6, 6, 6, 5, 6, 6, 6, 5, 5, 7, 6, 6, 6, 6, 5, 6, 7, 5, 5,
       7, 5, 5, 5, 5, 5, 5, 7, 7, 5, 5, 6, 1, 5, 1, 5, 6, 5, 6, 6, 1, 7,
       5, 6, 5, 6, 6, 6, 6, 6, 6, 5, 5, 6, 7, 5, 6, 6, 5, 6, 5, 5, 6, 6,
       5, 7, 6, 6, 6, 6, 6, 1, 1, 6, 1, 1, 5, 1, 5, 5, 5, 6, 6, 6, 6, 6,
       6, 6, 6, 6, 6, 5, 6, 5, 5, 5, 7, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6,
       6, 6, 6, 6, 5, 7, 5, 5, 7, 5, 7, 6, 6, 5, 6, 6, 6, 6, 6, 6, 6, 6,
       6, 6, 6, 6, 6, 5, 5, 6, 7, 6, 6, 7, 5, 5, 5, 5, 7, 6, 5, 5, 6, 7,
       5, 5, 5, 5, 5, 5, 5, 5, 5, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6,
       6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 5, 5, 1, 5, 5,
       1, 5, 5, 1, 5, 1, 6, 6, 6, 6, 6, 6, 6, 6, 6,

Avaliando modelo

In [97]:
acuracia = accuracy_score(y_test, y_pred)
acuracia

0.13812154696132597