# Experimentos

## Importando requisitos

In [17]:
import pandas
import os

## Abrindo a planilha

In [4]:
planilha = pandas.read_csv('../Dataset/DataSummary.csv')
planilha

,ID,Type,Name,Train,Test,Class,Length,ED (w=0),DTW (learned_w),DTW (w=100),Default rate,Data donor/editor
0,1,Image,Adiac,390,391,37,176,0.3887,0.3913 (3),0.3964,0.9591,A. Jalba
1,2,Image,ArrowHead,36,175,3,251,0.2000,0.2000 (0),0.2971,0.6057,L. Ye & E. Keogh
2,3,Spectro,Beef,30,30,5,470,0.3333,0.3333 (0),0.3667,0.8000,K. Kemsley & A. Bagnall
3,4,Image,BeetleFly,20,20,2,512,0.2500,0.3000 (7),0.3000,0.5000,J. Hills & A. Bagnall
4,5,Image,BirdChicken,20,20,2,512,0.4500,0.3000 (6),0.2500,0.5000,J. Hills & A. Bagnall
...,...,...,...,...,...,...,...,...,...,...,...,...
123,124,Spectrum,SemgHandMovementCh2,450,450,6,1500,0.6311,0.3622 (1),0.4156,0.8333,C.-C. M. Yeh
124,125,Spectrum,SemgHandSubjectCh2,450,450,5,1500,0.5956,0.2000 (3),0.2733,0.8000,C.-C. M. Yeh
125,126,Sensor,ShakeGestureWiimoteZ,50,50,10,Vary,0.4000,0.1600 (6),0.1400,0.9000,J. Guna
126,127,Simulated,SmoothSubspace,150,150,3,15,0.0933,0.0533 (1),0.1733,0.6667,X. Huang


## Filtrando na planilha os datasets selecionados

In [9]:
planilha = planilha[planilha['ID'].between(97, 128)]
planilha

,ID,Type,Name,Train,Test,Class,Length,ED (w=0),DTW (learned_w),DTW (w=100),Default rate,Data donor/editor
96,97,EOG,EOGVerticalSignal,362,362,12,1250,0.5580,0.5249 (2),0.5525,0.9144,E. Keogh & H. A. Dau
97,98,Spectro,EthanolLevel,504,500,4,1751,0.7260,0.7180 (1),0.7240,0.7480,A. Bagnall
98,99,Sensor,FreezerRegularTrain,150,2850,2,301,0.1951,0.0930 (1),0.1011,0.5000,REFIT project
99,100,Sensor,FreezerSmallTrain,28,2850,2,301,0.3242,0.3242 (0),0.2411,0.5000,REFIT project
100,101,HRM,Fungi,18,186,18,201,0.1774,0.1774 (0),0.1613,0.8978,W. Fonzi
101,102,Trajectory,GestureMidAirD1,208,130,26,Vary,0.4231,0.3615 (5),0.4308,0.9615,H. A. Dau
102,103,Trajectory,GestureMidAirD2,208,130,26,Vary,0.5077,0.4000 (6),0.3923,0.9615,H. A. Dau
103,104,Trajectory,GestureMidAirD3,208,130,26,Vary,0.6538,0.6231 (1),0.6769,0.9615,H. A. Dau
104,105,Sensor,GesturePebbleZ1,132,172,6,Vary,0.2674,0.1744 (2),0.2093,0.8140,I. Maglogiannis
105,106,Sensor,GesturePebbleZ2,146,158,6,Vary,0.3291,0.2215 (6),0.3291,0.8101,I. Maglogiannis


## Realizando experimentos no dataset da primeira linha da tabela

Obtendo o caminho do dataset de exemplo

In [16]:
dataset_exemplo = planilha.iloc[0]['Name']
dataset_exemplo

'EOGVerticalSignal'

In [19]:
dataset_dirname = os.path.join('../Dataset/UCRArchive_2018', dataset_exemplo)
dataset_dirname

'../Dataset/UCRArchive_2018/EOGVerticalSignal'

In [21]:
caminho_arquivo_treino = os.path.join(dataset_dirname, '{}_TRAIN.tsv'.format(dataset_exemplo))
caminho_arquivo_treino

'../Dataset/UCRArchive_2018/EOGVerticalSignal/EOGVerticalSignal_TRAIN.tsv'

In [22]:
caminho_arquivo_teste = os.path.join(dataset_dirname, '{}_TEST.tsv'.format((dataset_exemplo)))
caminho_arquivo_teste

'../Dataset/UCRArchive_2018/EOGVerticalSignal/EOGVerticalSignal_TEST.tsv'

Abrindo datasets

In [31]:
dataset_exemplo_treino = pandas.read_csv(caminho_arquivo_treino, sep='\t', header=None)
dataset_exemplo_treino

,0,1,2,3,4,5,6,7,8,9,...,1241,1242,1243,1244,1245,1246,1247,1248,1249,1250
0,1,-5.70320,-5.89550,-5.88780,-6.08000,-6.17230,-6.26460,-6.2568,-6.1491,-6.4414,...,-113.3100,-113.4100,-113.50000,-114.390000,-114.4800,-113.77000,-113.0700,-113.1600,-112.8500,-112.9400
1,1,-2.18020,-2.30860,-2.33690,-2.36520,-2.39360,-2.02190,-2.0502,-2.0786,-2.5069,...,108.3900,108.5600,108.53000,108.500000,108.4700,108.45000,108.4200,108.3900,108.1600,108.1300
2,1,6.70950,6.52680,6.34420,6.16160,5.97900,5.79640,5.6137,4.5311,2.7485,...,-34.9360,-35.1190,-35.30100,-35.484000,-35.6660,-34.94900,-35.1320,-35.3140,-34.5970,-34.7800
3,1,-0.91251,-0.72238,-0.53226,-0.74213,-0.95201,-1.16190,-1.5718,-1.7816,-1.1915,...,-173.8600,-174.0700,-173.68000,-173.890000,-174.7000,-174.71000,-174.9200,-175.1300,-174.7400,-174.3500
4,1,-5.44400,-5.32610,-4.10820,-3.69020,-3.57230,-3.45440,-3.0364,-2.6185,-2.5006,...,2.0864,1.8044,1.92230,2.040200,2.1582,2.27610,2.3940,2.5119,2.6299,2.7478
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
357,12,-4.32250,-2.52830,-2.83410,-2.83980,-2.84560,-2.85130,-4.3571,-4.3629,-4.3686,...,-2.1725,-1.3783,-0.08404,-0.089806,1.5044,-0.10134,-1.1071,-1.1129,-1.3186,-1.3244
358,12,-5.91600,-5.90050,-6.68500,-7.76950,-7.75400,-7.73850,-6.6230,-6.6075,-6.5920,...,32.0100,28.3260,25.44100,27.857000,32.0720,32.08800,31.9030,27.9190,27.9340,27.9500
359,12,2.66670,2.60940,2.55220,4.59490,1.63760,0.38033,2.4231,4.0658,2.3085,...,-42.8540,-42.9110,-42.96900,-43.026000,-44.3830,-45.84000,-44.4980,-44.5550,-44.6120,-47.1690
360,12,-1.22680,-1.24790,1.63100,1.50990,1.38880,3.16770,3.0465,2.9254,3.4043,...,-97.5090,-94.3310,-97.75200,-94.573000,-94.6940,-94.81500,-94.9360,-98.0570,-102.5800,-102.7000


In [32]:
dataset_exemplo_teste = pandas.read_csv(caminho_arquivo_teste, sep='\t', header=None)
dataset_exemplo_teste

,0,1,2,3,4,5,6,7,8,9,...,1241,1242,1243,1244,1245,1246,1247,1248,1249,1250
0,1,2.67520,2.68930,3.2034,4.01750,3.93150,3.94560,3.55970,3.87380,3.48790,...,-394.470,-392.450,-391.240,-390.830,-390.710,-390.900,-390.980,-390.870,-390.850,-390.740
1,1,6.84840,6.17140,5.6944,5.31730,5.14030,4.96330,4.18620,3.60920,2.73220,...,-145.670,-144.850,-144.220,-143.900,-143.680,-143.860,-143.530,-144.210,-144.790,-144.960
2,1,-4.91380,-4.87180,-4.8298,-4.98790,-5.14590,-4.50390,-4.66190,-3.72000,-3.57800,...,-169.270,-169.430,-169.590,-169.140,-169.100,-169.260,-169.420,-169.980,-170.730,-170.890
3,1,18.27800,18.29000,18.3020,18.31400,18.32600,19.13800,19.15000,19.86200,19.17400,...,308.330,307.840,308.350,307.670,307.380,308.290,308.300,308.310,307.830,307.840
4,1,-6.26350,-6.28940,-6.0153,-5.34120,-5.46710,-6.09300,-6.71890,-6.34470,-6.47060,...,39.229,38.503,38.077,37.551,37.425,36.499,36.374,37.048,36.922,36.796
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
357,12,2.02960,1.62900,1.2284,0.92786,0.72729,0.42672,0.42615,0.12558,0.12501,...,-12.375,-14.576,-14.576,-12.577,-12.577,-11.278,-11.279,-12.579,-11.280,-12.580
358,12,1.39790,1.59650,1.6951,0.89369,1.09230,1.29090,0.28948,0.08808,0.28668,...,132.660,132.460,132.660,132.850,133.450,133.950,133.850,134.050,133.850,134.350
359,12,1.90450,1.74240,1.8803,3.41830,2.15620,1.99420,2.13210,3.97010,4.10800,...,93.154,92.992,92.630,92.068,90.606,89.744,89.282,89.020,88.758,88.896
360,12,17.80400,16.97900,16.5540,16.02900,15.70400,15.07800,14.75300,13.22800,11.50300,...,-419.660,-419.990,-420.310,-420.040,-420.060,-420.390,-420.510,-420.840,-421.160,-421.490


### Aplicando algoritmos nos datasets

Importando algoritmos

In [33]:
from app.model.DynamicTimeWarping import DynamicTimeWarping
from app.model.DerivativeDynamicTimeWarping import DerivativeDynamicTimeWarping
from app.model.LongestCommonSubsequence import LongestCommonSubsequence
from app.model.SoftDynamicTimeWarping import SoftDynamicTimeWarping

Obtendo conjuntos de treino e teste: x e y

In [40]:
x_train = []
for linha in dataset_exemplo_treino.iloc[:, 1:].values:
    x_train.append(linha)
x_train

[array([  -5.7032,   -5.8955,   -5.8878, ..., -113.16  , -112.85  ,
        -112.94  ], shape=(1250,)),
 array([ -2.1802,  -2.3086,  -2.3369, ..., 108.39  , 108.16  , 108.13  ],
       shape=(1250,)),
 array([  6.7095,   6.5268,   6.3442, ..., -35.314 , -34.597 , -34.78  ],
       shape=(1250,)),
 array([  -0.91251,   -0.72238,   -0.53226, ..., -175.13   , -174.74   ,
        -174.35   ], shape=(1250,)),
 array([-5.444 , -5.3261, -4.1082, ...,  2.5119,  2.6299,  2.7478],
       shape=(1250,)),
 array([-29.207, -28.574, -28.241, ..., 102.63 , 102.36 , 102.9  ],
       shape=(1250,)),
 array([ -17.494,  -16.756,  -16.817, ..., -548.16 , -548.92 , -549.38 ],
       shape=(1250,)),
 array([ -37.921,  -35.45 ,  -32.58 , ..., -921.33 , -922.56 , -923.79 ],
       shape=(1250,)),
 array([ -9.0291,  -9.2402,  -9.2512, ..., -63.172 , -62.683 , -63.194 ],
       shape=(1250,)),
 array([-1.3589, -1.1494, -0.8399, ..., 64.361 , 64.27  , 64.18  ],
       shape=(1250,)),
 array([  10.287 ,    4.7215

In [43]:
y_train = []
for linha in dataset_exemplo_treino.iloc[:, 0].values:
    y_train.append(linha)
y_train

[np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(2),
 np.int64(2),
 np.int64(2),
 np.int64(2),
 np.int64(2),
 np.int64(2),
 np.int64(2),
 np.int64(2),
 np.int64(2),
 np.int64(2),
 np.int64(3),
 np.int64(3),
 np.int64(3),
 np.int64(3),
 np.int64(3),
 np.int64(3),
 np.int64(3),
 np.int64(3),
 np.int64(3),
 np.int64(3),
 np.int64(4),
 np.int64(4),
 np.int64(4),
 np.int64(4),
 np.int64(4),
 np.int64(4),
 np.int64(4),
 np.int64(4),
 np.int64(4),
 np.int64(4),
 np.int64(5),
 np.int64(5),
 np.int64(5),
 np.int64(5),
 np.int64(5),
 np.int64(5),
 np.int64(5),
 np.int64(5),
 np.int64(5),
 np.int64(5),
 np.int64(6),
 np.int64(6),
 np.int64(6),
 np.int64(6),
 np.int64(6),
 np.int64(6),
 np.int64(6),
 np.int64(6),
 np.int64(6),
 np.int64(6),
 np.int64(7),
 np.int64(7),
 np.int64(7),
 np.int64(7),
 np.int64(7),
 np.int64(7),
 np.int64(7),
 np.int64(7),
 np.int64(7),
 np.int64(7),
 np.int64(8),
 np.in

In [42]:
x_test = []
for linha in dataset_exemplo_teste.iloc[:, 1:].values:
    x_test.append(linha)
x_test

[array([   2.6752,    2.6893,    3.2034, ..., -390.87  , -390.85  ,
        -390.74  ], shape=(1250,)),
 array([   6.8484,    6.1714,    5.6944, ..., -144.21  , -144.79  ,
        -144.96  ], shape=(1250,)),
 array([  -4.9138,   -4.8718,   -4.8298, ..., -169.98  , -170.73  ,
        -170.89  ], shape=(1250,)),
 array([ 18.278,  18.29 ,  18.302, ..., 308.31 , 307.83 , 307.84 ],
       shape=(1250,)),
 array([-6.2635, -6.2894, -6.0153, ..., 37.048 , 36.922 , 36.796 ],
       shape=(1250,)),
 array([-2.9075, -3.4321, -3.5567, ..., -9.2573, -8.6819, -7.9065],
       shape=(1250,)),
 array([14.042, 13.721, 13.5  , ..., 51.104, 52.083, 52.363], shape=(1250,)),
 array([203.76, 204.14, 204.52, ..., 438.53, 438.61, 439.29], shape=(1250,)),
 array([ 1.4463,  1.4995,  2.2526, ..., 62.534 , 61.787 , 61.24  ],
       shape=(1250,)),
 array([  -1.8313,   -1.8628,   -1.8942, ..., -273.32  , -273.36  ,
        -273.39  ], shape=(1250,)),
 array([   1.6299,    1.5572,    1.1845, ..., -253.73  , -253.8 

In [44]:
y_test = []
for linha in dataset_exemplo_teste.iloc[:, 0].values:
    y_test.append(linha)
y_test

[np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(2),
 np.int64(2),
 np.int64(2),
 np.int64(2),
 np.int64(2),
 np.int64(2),
 np.int64(2),
 np.int64(2),
 np.int64(2),
 np.int64(2),
 np.int64(3),
 np.int64(3),
 np.int64(3),
 np.int64(3),
 np.int64(3),
 np.int64(3),
 np.int64(3),
 np.int64(3),
 np.int64(3),
 np.int64(3),
 np.int64(4),
 np.int64(4),
 np.int64(4),
 np.int64(4),
 np.int64(4),
 np.int64(4),
 np.int64(4),
 np.int64(4),
 np.int64(4),
 np.int64(4),
 np.int64(5),
 np.int64(5),
 np.int64(5),
 np.int64(5),
 np.int64(5),
 np.int64(5),
 np.int64(5),
 np.int64(5),
 np.int64(5),
 np.int64(5),
 np.int64(6),
 np.int64(6),
 np.int64(6),
 np.int64(6),
 np.int64(6),
 np.int64(6),
 np.int64(6),
 np.int64(6),
 np.int64(6),
 np.int64(6),
 np.int64(7),
 np.int64(7),
 np.int64(7),
 np.int64(7),
 np.int64(7),
 np.int64(7),
 np.int64(7),
 np.int64(7),
 np.int64(7),
 np.int64(7),
 np.int64(8),
 np.in

Normalizando os dados

In [45]:
from sklearn.preprocessing import StandardScaler

In [46]:
scaler = StandardScaler()

x_train = scaler.fit_transform(x_train)
x_test = scaler.fit_transform(x_test)